#pragma once

#include <stddef.h>
#include <stdint.h>

#include "sdkconfig.h"

/*
 * ASCII bytes "CSI1" interpreted as a 32-bit integer.
 *
 * The receiver checks this value to determine whether a UDP datagram
 * belongs to our CSI protocol.
 */
#define CSI_PACKET_MAGIC 0x43534931U

/*
 * Increment this whenever the binary packet layout changes.
 */
#define CSI_PACKET_VERSION 1U

/*
 * Flags stored in the packet's flags byte.
 */
#define CSI_PACKET_FLAG_FIRST_WORD_INVALID 0x01U
#define CSI_PACKET_FLAG_TRUNCATED          0x02U

/*
 * Fixed header layout:
 *
 * magic                 4 bytes
 * version               1 byte
 * flags                 1 byte
 * header length         2 bytes
 * sequence number       4 bytes
 * timestamp             8 bytes
 * source MAC            6 bytes
 * RSSI                   1 byte
 * noise floor            1 byte
 * channel                1 byte
 * reserved               1 byte
 * original CSI length    2 bytes
 * stored CSI length      2 bytes
 *
 * Total: 34 bytes
 */
#define CSI_PACKET_HEADER_SIZE 34U

/*
 * Maximum possible UDP payload generated by this project.
 */
#define CSI_PACKET_MAX_SIZE \
    (CSI_PACKET_HEADER_SIZE + CONFIG_CSI_MAX_DATA_LENGTH)
